<a href="https://colab.research.google.com/github/Sudar1612/MLP/blob/main/MLPEndTern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# Generate a dataset with 7 samples, 2 features, and 2 centers (clusters)
X, y = make_blobs(n_samples=7, n_features=2, centers=2, random_state=42)

# Initialize KMeans to find 8 clusters with random initialization
km = KMeans(n_clusters=8, init='random', n_init=1, random_state=42)

# Fit KMeans to the data
km.fit(X)


ValueError: n_samples=7 should be >= n_clusters=8.

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
a = [[-3], [0], [-2], [1], [-1],[ -4]]
mas = MaxAbsScaler()
scaled_a = mas.fit_transform(a)
print(scaled_a.max())

0.25


In [ ]:
scaled_a

array([[-0.75],
       [ 0.  ],
       [-0.5 ],
       [ 0.25],
       [-0.25],
       [-1.  ]])

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer(classes=['regular', 'medium', 'veg', 'non-veg'])
y_train = [['regular', 'veg'], ['medium', 'veg'], ['medium', 'non-veg']]
print(mlb.fit_transform(y_train))


[[1 0 1 0]
 [0 1 1 0]
 [0 1 0 1]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
data = ["apple", "orange", "banana", "apple", "grape", "orange", "grape"]
encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[0 3 1 0 2 3 2]


In [ ]:
encoder.transform(["orange"])

array([3])

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, Binarizer

data = [[1, 5], [5, 15], [0, 10], [1, 15]]
pipeline = Pipeline([('scaler', MinMaxScaler()), ('binarize', Binarizer(threshold=0.1))])
transformed_data = pipeline.fit_transform(data)

print(transformed_data)

[[1. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
from sklearn.decomposition import PCA

np.random.seed(42)
X = np.random.rand(100, 10)
pca = PCA(n_components=4)
X_pca = pca.fit_transform(X)
explained_variance = np.sum(pca.explained_variance_ratio_)


In [ ]:
explained_variance

0.5243949119023626

In [ ]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

# Sampled data
X = np.array([1, 2, 3, 4, 5])

# Reshape the features
X = X.reshape(-1, 1)

poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X)


In [ ]:
X

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
X.shape

(5, 1)

In [ ]:
X_poly

array([[  1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.],
       [  1.,   3.,   9.,  27.],
       [  1.,   4.,  16.,  64.],
       [  1.,   5.,  25., 125.]])

In [ ]:
data = [[1, 3], [2, 4]]
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=3, interaction_only=False)
print(pf.fit_transform(data))


[[ 1.  1.  3.  1.  3.  9.  1.  3.  9. 27.]
 [ 1.  2.  4.  4.  8. 16.  8. 16. 32. 64.]]


In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

X_train = [[1], [2], [3], [np.nan], [4], [np.nan], [5]]
pipe = Pipeline(steps=[('impute', SimpleImputer(strategy='mean')),
                       ('scale', StandardScaler())])
pipe.fit(X_train)
print(pipe[1])

StandardScaler()


In [5]:
pipe.transform(X_train)

array([[-1.67332005],
       [-0.83666003],
       [ 0.        ],
       [ 0.        ],
       [ 0.83666003],
       [ 0.        ],
       [ 1.67332005]])

In [6]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

X = np.array([[1.0, 2.0],
              [2.5, 3.5],
              [3.0, 5.0]])
y = np.array([0, 1, 0])

classifier = GaussianNB()
classifier.fit(X, y)

new_data = np.array([[2.0, 3.0]])
predicted_proba = classifier.predict_proba(new_data)

In [7]:
predicted_proba

array([[1., 0.]])

In [8]:
from sklearn.preprocessing import LabelEncoder

data = ["cat", "dog", "fish", "cat", "bird", "dog", "bird"]
encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)
print(encoded_data)


[1 2 3 1 0 2 0]


In [9]:
from sklearn.datasets import fetch_california_housing
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline, FeatureUnion

data = fetch_california_housing()
X = data.data

polynomial_transform = PolynomialFeatures(degree=2, include_bias=False)
pca_transform = PCA(n_components=5)
scaler = StandardScaler()

combined_features = FeatureUnion([('poly', polynomial_transform),
                                  ('pca', pca_transform)])

pipeline = Pipeline([('features', combined_features),
                     ('scaler', scaler)])

X_transformed = pipeline.fit_transform(X)
print(X_transformed.shape)


(20640, 49)


In [10]:
from sklearn.datasets import fetch_california_housing
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline, FeatureUnion

data = fetch_california_housing()
X = data.data

polynomial_transform = PolynomialFeatures(degree=3, include_bias=False)
pca_transform = PCA(n_components=5)
scaler = StandardScaler()

combined_features = FeatureUnion([('poly', polynomial_transform),
                                  ('pca', pca_transform)])

pipeline = Pipeline([('features', combined_features),
                     ('scaler', scaler)])

X_transformed = pipeline.fit_transform(X)
print(X_transformed.shape)


(20640, 169)


In [11]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[2.0, 5.0],
                 [4.0, 8.0],
                 [6.0, 12.0]])

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print("Original data:\n", data)
print("\nScaled data:\n", scaled_data)


Original data:
 [[ 2.  5.]
 [ 4.  8.]
 [ 6. 12.]]

Scaled data:
 [[-1.22474487 -1.16247639]
 [ 0.         -0.11624764]
 [ 1.22474487  1.27872403]]


In [12]:
data = [[1, 3],
        [2, 4]]

from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=3, interaction_only=True)
print(pf.fit_transform(data))


[[1. 1. 3. 3.]
 [1. 2. 4. 8.]]


In [14]:
from sklearn.neural_network import MLPClassifier
import numpy as np

data = np.array([[10, 3], [20, 5], [5, 1], [15, 4], [8, 2]])
# Corresponding target labels (0: No Purchase, 1: Purchase)
target = np.array([0, 1, 0, 1, 0])

# Initialize MLPClassifier with alpha parameter
clf = MLPClassifier(alpha=0.01, random_state=42)
clf.fit(data, target)

# Predict class labels
predicted_labels = clf.predict(data)



In [1]:
from sklearn.linear_model import Perceptron
# Sample data
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 0, 0, 1]

clf = Perceptron(tol=None, shuffle=False)
clf.fit(X, y)

print(clf.predict([[1, 1]]))


[1]


In [2]:
from sklearn.cluster import KMeans
import numpy as np

# Initialize data
X = np.array([[80, 20], [85, 21], [78, 25], [65, 30], [73, 30]])

# Create k-means model
kmeans = KMeans(n_clusters=3)

# Fit model to data
kmeans.fit(X)

# Predict cluster labels
labels = kmeans.labels_


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
